# Generated by Django 5.1.1 on 2024-10-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appportfolio', '0003_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulacion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre de titulación: ')),
                ('fechaInicio', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio: ')),
                ('fechaFin', models.DateField(blank=True, null=True, verbose_name='Fecha de fin: ')),
                ('notaMedia', models.IntegerField(blank=True, null=True, verbose_name='Nota media: ')),
                ('lugarEstudio', models.CharField(blank=True, max_length=50, null=True, verbose_name='Lugar de estudio: ')),
                ('nombreLugar', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre de lugar: ')),
                ('ciudad', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ciudad: ')),
                ('presencial', models.BooleanField(blank=True, max_length=50, null=True, verbose_name='Modalidad presencial: ')),
                ('observaciones', models.CharField(blank=True, max_length=100, null=True, verbose_name='Observaciones: ')),
            ],
            options={
                'verbose_name': 'Estudio',
                'verbose_name_plural': 'Estudios',
                'ordering': ['-id'],
            },
        ),
    ]
