# Generated by Django 5.1.1 on 2024-10-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appportfolio', '0004_estudio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('empresa', models.CharField(blank=True, max_length=50, null=True, verbose_name='Empresa')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Finalización')),
                ('observaciones', models.CharField(blank=True, max_length=50, null=True, verbose_name='Funciones')),
                ('categoria', models.CharField(blank=True, max_length=50, null=True, verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Experiencia',
                'verbose_name_plural': 'Experiencias',
                'ordering': ['empresa'],
            },
        ),
    ]
