# Generated by Django 4.1.5 on 2024-11-11 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appportfolio', '0011_alter_video_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=25, null=True, verbose_name='Nombre')),
                ('apellido1', models.CharField(blank=True, max_length=25, null=True, verbose_name='Primer apellido')),
                ('apellido2', models.CharField(blank=True, max_length=25, null=True, verbose_name='Segundo apellido')),
                ('email', models.EmailField(blank=True, max_length=40, null=True, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=9, null=True, verbose_name='Teléfono')),
            ],
            options={
                'verbose_name': 'Curriculum',
                'verbose_name_plural': 'Curriculums',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCurriculumExperiencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('curriculum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_detalleExp', to='appportfolio.curriculum')),
                ('experiencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='experiencia_detalle', to='appportfolio.experiencia')),
            ],
            options={
                'verbose_name': 'DetalleCurriculumExperiencia',
                'verbose_name_plural': 'DetalleCurriculumExperiencias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCurriculumEstudio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('curriculum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_detalleEst', to='appportfolio.curriculum')),
                ('estudio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estudio_detalle', to='appportfolio.estudio')),
            ],
            options={
                'verbose_name': 'DetalleCurriculumEstudio',
                'verbose_name_plural': 'DetalleCurriculumEstudios',
                'ordering': ['id'],
            },
        ),
    ]
